---

- hosts: all
  become: true
  pre_tasks:

  - name: Update and upgrade remote in Ubuntu servers
    apt:
      update_cache: yes
      upgrade: 'yes'
    when: ansible_distribution == "Ubuntu"

  - name: Installing dnf and epel-release
    yum:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Update and upgrade remote CentOS server
    dnf:
      update_cache: yes
      name:  "*"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Dpkg fixing in Ubuntu Servers
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

- hosts: Ubuntu
  become: true
  roles:
    - Ubuntu
    - Elastic_Search
    - Kibana
    - Logstash
    - Grafana
    - Prometheus
    - Lamp_Stack
    - Influxdb
    - Httpd_php
    - Mariadb

- hosts: CentOS
  become: true
  roles:
    - CentOS
    - Elastic_Search-CentOS
    - Kibana-CentOS
    - Logstash-CentOS
#    - Grafana-CentOS
    - Prometheus-CentOS
  # - Lamp_Stack
 #   - Influxdb-CentOS
    - Httpd_php-CentOS
    - Mariadb-CentOS

